#!/usr/bin/env bash

export REQUIRED_JAR=""
export REQUIRED_JAR=${REQUIRED_JAR}:/opt/slf4j-$SLF4J_VERSION/slf4j-api-$SLF4J_VERSION.jar
export REQUIRED_JAR=${REQUIRED_JAR}:/opt/slf4j-$SLF4J_VERSION/slf4j-simple-$SLF4J_VERSION.jar
export REQUIRED_JAR=${REQUIRED_JAR}:/opt/GMetrics-$GMETRICS_VERSION/GMetrics-$GMETRICS_VERSION.jar
export REQUIRED_JAR=${REQUIRED_JAR}:/opt/CodeNarc-$CODENARC_VERSION/CodeNarc-$CODENARC_VERSION.jar

export GROOVY_JAR=""
export GROOVY_JAR=${GROOVY_JAR}:${GROOVY_HOME}/lib/groovy-${GROOVY_VERSION}.jar
export GROOVY_JAR=${GROOVY_JAR}:${GROOVY_HOME}/lib/groovy-templates-${GROOVY_VERSION}.jar
export GROOVY_JAR=${GROOVY_JAR}:${GROOVY_HOME}/lib/groovy-xml-${GROOVY_VERSION}.jar

export CLASSPATH=${GROOVY_JAR}:${REQUIRED_JAR}

java -classpath ${CLASSPATH} org.codenarc.CodeNarc "$@"
